### ISSUE TITLE
Does not support Common Parameters

### ISSUE THREAD

**Issue by pauldemarco** [E-xyza/Apical#58]
The library currently does not support "Common Parameters for All Methods of a Path":

Parameters shared by all operations of a path can be defined on the path level instead of the operation level. Path-level parameters are inherited by all operations of that path. A typical use case are the GET/PUT/PATCH/DELETE operations that manipulate a resource 
accessed via a path parameter.
```yaml
paths:
  /user/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      summary: Gets a user by ID
      ...
    patch:
      summary: Updates an existing user with the specified ID
      ...
    delete:
      summary: Deletes the user with the specified ID
      ...
```
